// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/mnt/c/Users/Satyam Tiwari/Desktop/PhD/Ubuntu PhD/PhD/MC/TGenPhaseSpace/./basic2.cpp";

#endif
